### ISSUE TITLE
use with PixivUtil2

### ISSUE THREAD

**Issue by moono** [jerryli27/pixiv_dataset#1]
Hello,

I'm trying to use your 'colored_sketch_pair.csv' with PixivUtil2 as you mentioned in README.md.
How did you batch downloaded with that csv file?
I tried making list.txt file like below,
`
list.txt file

https://www.pixiv.net/member_illust.php?mode=medium&illust_id=14646322
https://www.pixiv.net/member_illust.php?mode=medium&illust_id=14577906
`

and choose option 4 in PixivUtil2 program like below,

![image](https://user-images.githubusercontent.com/6761398/30051886-9adfc5c2-925e-11e7-9cd3-fa2e7a77e330.png)

but no action what so ever.

Any hint appreciated!! Thank you.

**Comment by jerryli27** [comment]
Hi moono,

PixivUtil2 documentation was not clear on option 4. "Download from list" is for downloading all images by a list of members, NOT a list of image ids. I was confused as well. You can use option 2, "download by image_id" and copy/paste a list of image ids separated by space. 

It should look something like this, although in your case it should not say "already downloaded": 


```
PixivDownloader2 version 20170813-beta1
https://github.com/Nandaka/PixivUtil2/releases
Donate at https://bit.ly/PixivUtilDonation
1. Download by member_id
2. Download by image_id
3. Download by tags
4. Download from list
5. Download from bookmarked artists (bookmark.php?type=user)
6. Download from bookmarked images (bookmark.php)
7. Download from tags list
8. Download new illust from bookmarked members (bookmark_new_illust.php)
9. Download by Title/Caption
10. Download by Tag and Member Id
11. Download Member Bookmark
12. Download by Group Id
------------------------
d. Manage database
e. Export online bookmark
m. Export online user bookmark
r. Reload config.ini
p. Print config.ini
x. Exit
Input: 2
Image ids: 14646322 14577906
Found 2 ids 
Processing Image Id: 14646322
Already downloaded: 14646322
Processing Image Id: 14577906
Already downloaded: 14577906
PixivDownloader2 version 20170813-beta1
```

Images downloaded should be placed under pixiv_downloaded folder. Each painter will have his/her separate folder . Let me know if you have any other questions!

**Comment by moono** [comment]
Hello,
Thank you for your suggestion, I'll try to use option 2.
Also for the screen shot I attached, it was my language setting issue.
I managed to solve it with changing my language setting in Pixiv website to English.

**Comment by jerryli27** [comment]
Cool. You may close the issue if option 2 works.
